### PR TITLE
Update icons

### LINKED ISSUE #181: Update icons
With the new vscode icons being released soon 🎉 (https://github.com/microsoft/vscode/issues/8017) ... your extension sidebar icon looks a little weird:

Screen Shot 2019-07-10 at 6 58 29 AM

> Picture taken in Visual Studio Code - Insiders (which already has the new icons)

 I will open a PR with my updated icons throughout this project to follow the new icon styles

### PR DESCRIPTION
**Pull request by johnletey**
VS Code is updating its icons to [use an outline style](https://github.com/microsoft/vscode/issues/8017#issuecomment-509349133). With this change now released on stable, I've gone through and updated some of the icons used in the Todo Tree extension to match this new style.

**Note:** Still working on the rest of the icons, should be done shortly!

Closes #181

### CODE REVIEW

**Comment by Gruntfuggly** [comment]
Sorry - didn't mean to mark it as ready for review.

**Comment by johnletey** [comment]
Totally fine @Gruntfuggly!

**Comment by johnletey** [comment]
@Gruntfuggly @kanlukasz I'm done updating the icons! Please do have a look!

I'm not that big of a fan of the new sidebar icon, and it doesn't really match the style of the official sidebar icons. @misolori Since you use this extension, do you mind having a look and seeing where I could improve 😄. Also wouldn't mind if you critiqued the rest of the icons. [Figma](https://www.figma.com/file/14zPkKoSmMADElHJOJNYW6/todo-tree-icons)

**Comment by Gruntfuggly** [comment]
They all look pretty good to me. I think the sidebar icon just needs a bit more 'shape' to the tree. I originally generated it from the extension icon - I'm guessing you've taken the old sidebar icon and made it an outline rather than filled - would it be worth doing that directly from the extension icon?

**Comment by johnletey** [comment]
> I'm guessing you've taken the old sidebar icon and made it an outline rather than filled - would it be worth doing that directly from the extension icon?

Yes, that's what I did ... what do you mean by doing that directly from the extension icon?

**Comment by Gruntfuggly** [comment]
The extension icon is a .png and I think I converted it to a svg and removed the colour - I was wondering if that process had somehow changed the shape a bit.

However, I've just looked at the icons on the Figma page and the sidebar icon looks much better - when rendered in the sidebar it looks a bit different to me? Maybe it just needs to be slightly bigger?

**Comment by johnletey** [comment]
> Maybe it just needs to be slightly bigger?

Agree ... just changed!

**Comment by kanlukasz** [comment]
Looks good for me too 👌

**Comment by misolori** [comment]
👏  Great job  @johnletey, they look great!

**Comment by johnletey** [comment]
Awesome ... thank you so much @misolori and @kanlukasz!

**Comment by Gruntfuggly** [comment]
Are you happy for me to merge this now?

**Comment by johnletey** [comment]
Totally @Gruntfuggly! Merge it 🚀

**Comment by Gruntfuggly** [comment]
Hi John - had you intended to change the colours of some of the icons? I've noticed that some are slightly different.

**Comment by johnletey** [comment]
No I did not ... this must be by mistake!

What icons have you noticed in particularly @Gruntfuggly?

**Comment by Gruntfuggly** [comment]
Some of the todo-<colour>.svg icons have subtlety different colours. The magenta icon is white, which is obviously a mistake.

I wanted to check before I reverted them back to the original colours - I thought you may have brightened some of them as they have less 'body' to them now. If I change the red one back to it's original colour it's harder to see, so I've made that one a bit brighter.

**Comment by johnletey** [comment]
> Some of the todo-.svg icons have subtlety different colours. The magenta icon is white, which is obviously a mistake.
> 
> I wanted to check before I reverted them back to the original colours - I thought you may have brightened some of them as they have less 'body' to them now. If I change the red one back to it's original colour it's harder to see, so I've made that one a bit brighter.

oh ... now I know what you're talking about! so yes, the magenta icon is a mistake ... but the others I purposely changed to match similar official vscode icons ... you are free to change back though, I just wanted to be as close to the official icons as possible!

**Comment by Gruntfuggly** [comment]
Which icons where you matching them against?

**Comment by johnletey** [comment]
@Gruntfuggly All of the docker `status` icons (like stop, ok, pause, start, warning and so on) ... https://github.com/microsoft/vscode-docker/pull/1192

**Pull request merged**
