### PR TITLE
localization support for zh-cn

### PR DESCRIPTION
**Pull request by loniceras**
A localization support for zh-cn. See also #355.

### CODE REVIEW

**Comment by Gruntfuggly** [comment]
Hi - thanks for this. How does it work? Does it just work out of the box?

**Comment by loniceras** [comment]
That's right. Which translation is used depends on the language used by VSCode. [An example](https://github.com/shanalikhan/code-settings-sync).

**Comment by Gruntfuggly** [comment]
Hi - I've merged this now. I've added a new context menu item:
"Toggle Compact Folders".
Can you provide a translation please?

Sorry, but I expect I'll have to ask you each time I add something!

**Comment by loniceras** [comment]
Hi! The translation of "Toggle Compact Folders" may be "紧凑/宽松形式呈现文件夹".

What's more, there's no dependency between the nls files and `package.json`. You can add anything in the same way as before. If you like, you can fill in `package.json` and `package.nls.json` (in English) in similar forms, which is helpful for new translations. When translations need to be added or updated, I or other contributors will submit a PR to add or improve the translations. All in all, the lack of nls files (except `package.nls.json`) will not affect the use of the extension. In addition, if you want to ask me for translations, I'm also glad to provide translation suggestions.

**Comment by Gruntfuggly** [comment]
Thank you!

**Pull request merged**
