### PR TITLE
Faster, more accurate and more robust regex

### PR DESCRIPTION
**Pull request by Arcitec**
The default regex was sort of making me itch, as someone who's the "go-to guy" for writing correct regex patterns. It had lots of room for improvement, to increase accuracy and support more languages, and improve speed. This contribution takes care of the pattern once and for all.

Closes #189 
Closes #47

Supersedes almost all "alternative language" code in the [wiki](https://github.com/Gruntfuggly/todo-tree/wiki/Configuration-Examples), making the wiki nearly pointless. Only the Ocaml and PQSL sections in the wiki remain relevant after these changes. Those languages' comment patterns are a bit too esoteric for general inclusion in the regex, in my opinion, and should remain in the wiki.

Commit message below:

---

Enhances the default regex to support more programming languages while
also increasing the ACCURACY and PERFORMANCE by adding bounds checks
and other correctness checks.

All `\s` (whitespace) selectors are now replaced with higher-performing
and more accurate `[ \\t]` (spaces and tabs). JavaScript lacks Perl's
`\h` selector for "horizontal whitespace", so we MUST be more explicit
here to get the same benefits. Why this change? Because `\s` matches new
lines, which means that the entire matching slows down and breaks since
it also checks across line boundaries, which is very bad. So we MUST use
`[ \\t]` for correctness. And programming only uses spaces or tabs, so
we don't need the additional Unicode Whitespace that Perl's `\h` has.

This new regex looks for one of the following:
(When we say "whitespace" below, we only mean spaces or tabs.)

1. `//` (most languages; is unique enough to not need extra bounds...
   is used for "integer division" in some languages, but that's rare
   in actual code, and wouldn't be a false positive anyway since the
   user would ALSO have to put a tag word after their "//" operator)
2. `#` (Python, etc)
3. `<start of line, OR one or more whitespace>--` (Lua etc; the spaces
   increase speed and avoids false positives from syntax
   such as "i--" or "--i".)
4. `<!--` (XML/HTML)
5. `;`
6. `<either "/", OR "start-of-line followed by zero or more
    whitespace"><1 or more "*">` (this matches multiline comments;
    matches "/***** TODO", "* TODO", etc and completely avoids false
    positives. there are no risks thanks to the strict pattern.)
7. `<start of line>` (this is a strict pattern and ensures that we
    are able to match tags within multiline comments, such as inside
    the XML/HTML `<!-- lines... -->` blocks.)

When one of the patterns above match, we check that it's followed by
ALL of the below:

1. `<zero or more whitespace>` (this handles the fact that some
   people like to write `//TODO` and other people write `// TODO`.)
2. Then `<optional "@">` (this handles the `@todo` syntax used in
   JavaDoc, JavaScript, PHP, etc. but note that we still need to
   extend the default tags with lowercase variants if we want to
   actually match them)
3. Then it matches any of the tags.
4. Then `\b` which performs a boundary check to ensure that nothing
   follows after the matched tag. So "// NOTE:" and "// NOTE" will
   match, but not "// NOTEDHEHE".

Lastly, we have the alternative pattern which looks for a markdown
"todo" list item, as seen before `^[ \\t]*- \\[ \\])` (with the
only modification being the improved whitespace pattern here).

### CODE REVIEW

**Comment by VideoPlayerCode** [comment]
Also note that I wanted to double the performance of the JavaScript regex matching (which I assume is what's used for the general highlighter for unsaved files, as asked here https://github.com/Gruntfuggly/todo-tree/issues/249).

However, as soon as I improved the performance of the pattern, the regex stopped finding files. So I assume that ripgrep doesn't support the syntax.

Here's the improvement I _wanted_ to also make, but couldn't, due to that problem:

1. Go to https://jsbench.me/
2. In the top box, write:
```js
var test = "// TODO";
var rgx = /((\/\/|#|[ \t]+--|<!--|;|(\/|^[ \t]*)\*+|^)[ \t]*@?(TODO|FIXME|BUG|XXX|NOTE)\b|^[ \t]*- \[ \])/;
var matches = 0;
if (test.match(rgx)) {
  matches++;
}
```
3. In the bottom box, write:
```js
var test = "// TODO";
var rgx = /(?:(?:\/\/|#|[ \t]+--|<!--|;|(?:\/|^[ \t]*)\*+|^)[ \t]*@?(?:TODO|FIXME|BUG|XXX|NOTE)\b|^[ \t]*- \[ \])/;
var matches = 0;
if (test.match(rgx)) {
  matches++;
}
```
4. Run the test. The result will show you that the latter is TWICE as fast (for me: `22,747,101 ops/s` instead of `12,214,451 ops/s`).

The secret is that the latter pattern tells the regex engine "do not waste any energy saving the parenthesis (capture) groups to memory". That's what the `(?:)` syntax does. But unfortunately, it broke things, so it couldn't be included in this pull request. If you have any idea why it breaks (despite the fact that VSCode runs on JavaScript and that `(?:)` is a valid JavaScript regex pattern), then please let me know and I can update the pull request.

**Comment by VideoPlayerCode** [comment]
Lastly, here's an intentionally messy and silly `.js` document which tests all kinds of these patterns:

```js
* FIXME asd9
a * TODO asd4 // good, this should not match
a / TODO asd5 // good, this should not match
lua style -- TODO asd15
lua style --TODO will also match; minor issue of "--todo" etc false positives, but what kinda idiot names their vars todo or FIXME? "return blah --TODO" is a common code style and must be matched.
for (var todo=0; todo<10; --todo) { // Intentional issue; nobody should use such idiotic variable names, so won't be an issue for real programmers.
    bar = todo
}
x-- TODO // good, this should not match
--x TODO // good, this should not match
/*
 * @todo foo1
 */
a = String()

/**** TODO asd123
 * TODO asd2
 * @TODO what
 * @todo this will intentionally only match if case-sensitive is turned off, or if "todo" is added to the list of tags
 # TODO  asd 3
 # TODODAMN should not match (fixed by adding \b after the tag (boundary check))
 ** TODO this should match, since our pattern matches 1 or more asterisks in a row
*/
1 // TODO: asd6
<!--
 TODO foo7
->
 * TODO  asd8
var x = 823; TODO asd10
var a = 10;
let foo = 100;
```

**Comment by VideoPlayerCode** [comment]
I'll also add the following thought: Yes, this makes the regex more complex-looking. So what? It's now faster, more robust and supports more programming languages. This kind of _internal_ pattern is supposed to be _fast_, _universally applicable_ and _correct_, which means that optimizations have to be used, and that's not necessarily readable by regex newbies. ;-) If someone doesn't understand the pattern, that's their problem, not ours. Meanwhile, _we_ should focus on speed and correctness. Furthermore, the commit message (which will be added to the git log) fully explains the pattern.

**Comment by Gruntfuggly** [comment]
Ripgrep uses rust regular expressions, which is why I expect it doesn't work.

**Comment by VideoPlayerCode** [comment]
@Gruntfuggly Hmm, but Rust says that `(?:<expression>)` syntax is indeed non-capturing groups: https://www.eclipse.org/paho/files/rustdoc/regex/index.html#grouping-and-flags

Maybe ripgrep has disabled that behavior. Even more likely is the possibility that ripgrep automatically inserts `?:` after every `(` for speed, which in turn makes the regex `(?:?:` if we provided a `(?:` ourselves, which breaks the regex.

I'd be interested in coding a fix for all of this, so that we get `(?:` syntax in JavaScript land, and `(` syntax when sent to Ripgrep. For the best of both worlds (2x faster matching in JS land).

I assume that `highlights.js : getCustomHighlightSettings` is the function that is used for matching highlights in the currently open document? At least it seems to me like Todo Tree uses JS (in VSCode natively) for matching open documents, and uses ripgrep only for the main tree view.

**Comment by VideoPlayerCode** [comment]
@Gruntfuggly Success. I've finished implementing the 2x speedup for the internal JS regex matcher. Commit incoming...

**Comment by VideoPlayerCode** [comment]
@Gruntfuggly We may want to lower the default 500ms highlight timeout since the regex matching is 2x faster now. Or perhaps leave it up to the users as usual. What do you think?

**Comment by VideoPlayerCode** [comment]
By the way, I've noticed a bug(?). The function `utils.js : getRegexForRipGrep()` is not called anywhere. Instead, ripgrep seems to use the raw `getRegexSource` instead.

**Comment by BurntSushi** [comment]
> Edit: Yes, I just checked the ripgrep source. It translates all groups to (?: for speed. 

Can you show me where you saw this? ripgrep does not do this, but I'm not sure where your confusion is.

As far as ripgrep is concerned, for its default regex engine, there is absolutely zero performance difference between `(re)` and `(?:re)`.

**Comment by alexlya** [comment]
While we are talking about updating "todo-recognizing" regex (I did not read full discussion), can we please also add support to ColdFusion style comments which is similar to html but has 3 dashes instead of 2:
```
<!---
```
I updated regex on my system, but it would be nice to have this out-of-the-box, and the change is trivial, really.

**Comment by yaznagv** [comment]
for recognizing TODO regex, can be added support for Javascript block comments
```
/** TODO some thing to do
*/
```

**Comment by octoshrimpy** [comment]
# 👍
Looks good! Just missing branch conflicts.

**Pull request closed without merging**
