### PR TITLE
Multilanguage support and a deprecated entry in configuration

### PR DESCRIPTION
**Pull request by loniceras**
Hi! I made a multilanguage support for zh-cn in commit `e24ad00`. When I was doing translation, I found there might be a deprecated entry in configuration, but I was not sure. That was `todo-tree.tree.showScanModeButton`. I'v tried it in different cases, but all failed. The other entry `todo-tree.tree.buttons.scanMode` behaved correctly. So I supposed `todo-tree.tree.showScanModeButton` was deprecated and modified it in commit `e400c0f`.

### CODE REVIEW

**Comment by Gruntfuggly** [comment]
Hi - why have you closed this?

**Comment by loniceras** [comment]
Hi! I'm not sured if this extension needs a  localization support. So I closed this pr.

**Comment by Gruntfuggly** [comment]
It's probably a good idea - I've just got a bit of a backlog which is why I haven't looked at your pull request yet.

**Comment by loniceras** [comment]
I understand.  I will submit a new pr when you have finished these backlogs.

**Pull request closed without merging**
