### PR TITLE
Improved default regex expression

### PR DESCRIPTION
**Pull request by marcosfreitas**
This improvement match comments in javascript files like:
/**
 * Description of an script...
 * TODO description
 */

### CODE REVIEW

**Comment by kanlukasz** [comment]
My suggestion: https://github.com/Gruntfuggly/todo-tree/issues/111#issuecomment-457991437

**Comment by vSanjo** [comment]
Just want to add my `2c`. This is the default regex I've decided to use. I wasn't impressed with the current standard, so I'm glad @lazyislazy brought it to the surface and hope @marcosfreitas has brought it to attention.

**Comment by VideoPlayerCode** [comment]
Note: This pull request (#47) just adds a loose `*` (asterisk) to the pattern, without any bounds. It's just going to massively slow down the regex since anytime an asterisk appears _anywhere_ in code or text (such as in multiplication), the whole pattern will attempt matching. There are much better ways to add single-asterisk support. Either way, there's a brand new pattern in #251 which handles everything properly.

**Comment by Gruntfuggly** [comment]
Hi - sorry it's taken so long to respond to this. I don't change the default regex anymore as it causes issues for existing users. It's easy enough each user to configure the regex to their own requirements, so I am going to close this.

Thanks anyway.

**Pull request closed without merging**
